### ISSUE TITLE
Problem when increasing batchsize

### ISSUE THREAD

**Issue by wr0112358** [VISION-SJTU/USOT#7]
When increasing the Batchsize from the default 12 to 64 this error occurs:
  File "/USOT/lib/models/models.py", line 276, in forward
    bbox_pred_to_img = self.pred_offset_to_image_bbox(off_forward_bbox, batch)
  File "/USOT/lib/models/models.py", line 145, in pred_offset_to_image_bbox
    pred_x1 = self.grid_to_search_x - bbox_pred[:, 0, ...].unsqueeze(1)
RuntimeError: The size of tensor a (64) must match the size of tensor b (256) at non-singleton dimension 0

The sizes of the relevant variables for batch size 12:
  self.grid_to_search_x / y = [48, 1, 25, 25]
  bbox_pred = [48, 4, 25, 25]

and for batch size 64:
self.grid_to_search_x / y = [64, 1, 25, 25]
bbox_pred = [256, 4, 25, 25]

**Comment by zhengjilai** [comment]
Sorry. Since I have never tried such a large batch size, this is definetely a bug which I fail to notice. Fortunately, this problem can be fixed easily.  

In line 122-123 in file [model.py](https://github.com/VISION-SJTU/USOT/blob/main/lib/models/models.py), you may notice that the dimension 0 of variable "self.grid_to_search_x / y" is repeated "self.maximum_batch * self.mem_size" times. Here the choice of "self.maximum_batch" is the reason why the dimension 0 is not large enough as shown above. This attribute is assigned when the USOT class is initialized. You can revise that variable (to 64) during initialization for fixing this bug. The default maximum batch I set while coding this project (purely at random), is 16 actually.

**Comment by wr0112358** [comment]
Thank you. This solution works.
